FROM ubuntu as clone

# Update aptitude with new repo
RUN apt-get update \
 && apt-get install -y git

RUN git clone https://github.com/ludeeus/container


FROM python:3.9-slim-buster
  
ENV DEBIAN_FRONTEND=noninteractive
ENV CONTAINER_TYPE=integration-debian
ENV DEVCONTAINER=True

COPY --from=clone /container/rootfs/common /

RUN  \
    apt update \
    && apt install -y --no-install-recommends --allow-downgrades  \
        bash \
        ca-certificates \
        gcc \
        git \
        libavcodec-dev \
        libc-dev \
        libffi-dev \
        make \
        nano \
        openssh-client \
        python3-dev \
        python3-pip \
        python3 \
        wget \
        libjpeg-dev \
        zlib1g-dev \
    && python3 -m pip install --no-cache-dir -U  \
        pip \
        setuptools \
        wheel \
    && python3 -m pip install --upgrade pip \
    && python3 -m pip install --no-cache-dir -U -r requirements_test.txt \
    && chmod +x /usr/bin/container \
    && ln -s /usr/bin/python3 /usr/bin/python \
    && mkdir -p /config/custom_components \
    && rm -fr /var/lib/apt/lists/* \
    && find /usr/local \( -type d -a -name test -o -name tests -o -name '__pycache__' \) -o \( -type f -a -name '*.pyc' -o -name '*.pyo' \) -exec rm -rf '{}' \; \
    && rm -fr /tmp/* /var/{cache,log}/*



